# Generated by Django 5.1 on 2024-08-25 12:21

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Regions',
            fields=[
                ('slug', models.SlugField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100)),
                ('parent_slug', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='RateListAPI.regions')),
            ],
        ),
        migrations.CreateModel(
            name='Ports',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=5)),
                ('name', models.CharField(max_length=100)),
                ('parent_slug', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='RateListAPI.regions')),
            ],
        ),
    ]
