# Generated by Django 5.1 on 2024-08-25 12:31

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('RateListAPI', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Prices',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('day', models.DateField()),
                ('price', models.IntegerField()),
                ('dest_code', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='destination_prices', to='RateListAPI.ports')),
                ('orig_code', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='origin_prices', to='RateListAPI.ports')),
            ],
        ),
    ]
